"use client";
import React, { createContext, useContext, useEffect, useState } from "react";

export type LanguageCode =
  | "en" | "ru" | "vi" | "tr" | "es" | "ar" | "bg" | "cz" | "dk" | "de"
  | "el" | "fi" | "fr" | "hi" | "hu" | "id" | "it" | "ja" | "ko" | "nl"
  | "no" | "pl" | "pt";

export type CurrencyCode = "AED" | "USD" | "EUR" | "GBP" | "INR" | "RUB" | "CNY";

interface PreferencesContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currency: CurrencyCode;
  setCurrency: (curr: CurrencyCode) => void;
  formatPrice: (priceVal: number, type?: "buy" | "rent") => string;
  formatArea: (areaStr: string) => string;
  t: (key: string) => string;
}

const PreferencesContext = createContext<PreferencesContextType>({
  language: "en",
  setLanguage: () => {},
  currency: "AED",
  setCurrency: () => {},
  formatPrice: (p) => `AED ${p.toLocaleString()}`,
  formatArea: (a) => a,
  t: (k) => k,
});

// Exchange rates: 1 AED = X foreign currency, or X AED = 1 foreign currency
// Base is AED. Rates relative to 1 AED:
const CURRENCY_CONVERSION: Record<CurrencyCode, { rate: number; prefix: string; suffix: string }> = {
  AED: { rate: 1.0, prefix: "AED ", suffix: "" },
  USD: { rate: 0.2723, prefix: "$", suffix: "" },
  EUR: { rate: 0.2513, prefix: "€", suffix: "" },
  GBP: { rate: 0.2151, prefix: "£", suffix: "" },
  INR: { rate: 22.68, prefix: "₹", suffix: "" },
  RUB: { rate: 24.32, prefix: "₽", suffix: "" },
  CNY: { rate: 1.972, prefix: "¥", suffix: "" },
};

// Language dictionary
const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
  en: {
    buy: "Buy",
    rent: "Rent",
    newProjects: "New Projects",
    toolsInsights: "Tools & Insights",
    findAgents: "Find Agents",
    loginSignup: "Login / Signup",
    savedProperties: "Saved Properties",
    exploreBlog: "Explore Blog",
    searchPlaceholder: "Search properties...",
    allCategories: "All Categories",
    apartments: "Apartments",
    villas: "Villas",
    townhouses: "Townhouses",
    penthouses: "Penthouses",
    plots: "Plots",
    beds: "Beds",
    baths: "Baths",
    area: "Area",
    priceRange: "Price Range",
    searchButton: "Search Properties",
    overview: "Overview",
    amenities: "Amenities",
    paymentPlan: "Payment Plan",
    location: "Location & Nearby",
    pricesTrends: "Prices & Trends",
    similarProperties: "Similar Properties",
    propertyPrice: "Property Price",
    contactAgent: "Contact Agent",
    sendInquiry: "Send Inquiry",
    callUs: "Call Us",
    chat: "Chat",
    save: "Save",
    saved: "Saved",
    mortgageCalculator: "Mortgage Calculator",
    downPayment: "Down Payment",
    interestRate: "Interest Rate",
    loanTerm: "Loan Term",
    monthlyPayment: "Estimated Monthly Payment",
    upfrontCosts: "Upfront Costs",
    dldFee: "DLD Fee (4%)",
    agencyFee: "Agency Fee (2%)",
    mortgageRegistration: "Mortgage Registration (0.25%)",
    totalUpfrontRequired: "Total Upfront Cash Required",
    verifiedAgent: "Verified Agent",
    responseTime: "Response Time",
    languagesSpoken: "Languages Spoken",
    whatsApp: "WhatsApp",
    all: "All",
    searchTitle: "Discover Luxury Living Across UAE",
    searchSubtitle: "Explore our curated collection of extraordinary apartments, villas, and penthouses.",
    reset: "Reset Filters",
    sortBy: "Sort By",
    default: "Default",
    priceAsc: "Price: Low to High",
    priceDesc: "Price: High to Low",
    "Discover Extraordinary Living Across UAE": "Discover Extraordinary Living Across UAE",
    "AA Real Estate DEVELOPMENTS": "AA Real Estate DEVELOPMENTS",
    "Luxury Villas Designed For Elevated Living": "Luxury Villas Designed For Elevated Living",
    "UNRIVALED SOPHISTICATION": "UNRIVALED SOPHISTICATION",
    "Premium Apartments In Prime Locations": "Premium Apartments In Prime Locations",
    "CURATED URBAN LIVING": "CURATED URBAN LIVING",
    "Smart Property Discovery Experience": "Smart Property Discovery Experience",
    "AI-POWERED SEARCH": "AI-POWERED SEARCH",
    "Where Investment Meets Lifestyle": "Where Investment Meets Lifestyle",
    "GENERATE SECURE WEALTH": "GENERATE SECURE WEALTH",
    "Invest In UAE’s Future Landmarks": "Invest In UAE’s Future Landmarks",
    "EXCLUSIVE CAPITAL APPRECIATION": "EXCLUSIVE CAPITAL APPRECIATION",
    "3,500+ Pro Users": "3,500+ Pro Users",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "BEGIN YOUR JOURNEY WITH AA REAL ESTATE",
    "Luxury Real Estate Across the UAE": "Luxury Real Estate Across the UAE",
    "Explore Properties": "Explore Properties",
    "Book A Consultation": "Book A Consultation",
    "Why Us?": "Why Us?",
    "Why AA Real Estate?": "Why AA Real Estate?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.",
    "This isn’t just about real estate.": "This isn’t just about real estate.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.",
  },
  ru: {
    buy: "Купить",
    rent: "Аренда",
    newProjects: "Новые проекты",
    toolsInsights: "Инструменты",
    findAgents: "Найти агента",
    loginSignup: "Войти / Регистрация",
    savedProperties: "Сохраненные",
    exploreBlog: "Блог",
    searchPlaceholder: "Поиск недвижимости...",
    allCategories: "Все категории",
    apartments: "Апартаменты",
    villas: "Виллы",
    townhouses: "Таунхаусы",
    penthouses: "Пентхаусы",
    plots: "Участки",
    beds: "Спальни",
    baths: "Ванные",
    area: "Площадь",
    priceRange: "Диапазон цен",
    searchButton: "Найти варианты",
    overview: "Обзор",
    amenities: "Удобства",
    paymentPlan: "План оплаты",
    location: "Расположение",
    pricesTrends: "Цены и тенденции",
    similarProperties: "Похожие объекты",
    propertyPrice: "Цена объекта",
    contactAgent: "Связаться с агентом",
    sendInquiry: "Отправить запрос",
    callUs: "Позвонить",
    chat: "Чат",
    save: "В избранное",
    saved: "В избранном",
    mortgageCalculator: "Ипотечный калькулятор",
    downPayment: "Первоначальный взнос",
    interestRate: "Процентная ставка",
    loanTerm: "Срок кредита",
    monthlyPayment: "Ежемесячный платеж",
    upfrontCosts: "Дополнительные расходы",
    dldFee: "Регистрация DLD (4%)",
    agencyFee: "Агентская комиссия (2%)",
    mortgageRegistration: "Регистрация ипотеки (0.25%)",
    totalUpfrontRequired: "Всего первоначальных средств",
    verifiedAgent: "Проверенный агент",
    responseTime: "Время ответа",
    languagesSpoken: "Языки",
    whatsApp: "WhatsApp",
    all: "Все",
    searchTitle: "Откройте для себя элитную жизнь в ОАЭ",
    searchSubtitle: "Исследуйте нашу коллекцию эксклюзивных апартаментов, вилл и пентхаусов.",
    reset: "Сбросить фильтры",
    sortBy: "Сортировка",
    default: "По умолчанию",
    priceAsc: "Сначала дешевые",
    priceDesc: "Сначала дорогие",
    "Discover Extraordinary Living Across UAE": "Откройте для себя необыкновенную жизнь в ОАЭ",
    "AA Real Estate DEVELOPMENTS": "Девелопмент AA Real Estate",
    "Luxury Villas Designed For Elevated Living": "Роскошные виллы для возвышенного образа жизни",
    "UNRIVALED SOPHISTICATION": "НЕПРЕВЗОЙДЕННАЯ ИЗЫСКАННОСТЬ",
    "Premium Apartments In Prime Locations": "Премиальные апартаменты в лучших районах",
    "CURATED URBAN LIVING": "ЭКСКЛЮЗИВНАЯ ГОРОДСКАЯ ЖИЗНЬ",
    "Smart Property Discovery Experience": "Умный поиск и подбор недвижимости",
    "AI-POWERED SEARCH": "ПОИСК НА БАЗЕ ИСКУССТВЕННОГО ИНТЕЛЛЕКТА",
    "Where Investment Meets Lifestyle": "Где инвестиции встречаются с качеством жизни",
    "GENERATE SECURE WEALTH": "СОЗДАВАЙТЕ НАДЕЖНЫЙ КАПИТАЛ",
    "Invest In UAE’s Future Landmarks": "Инвестируйте в будущие достопримечательности ОАЭ",
    "EXCLUSIVE CAPITAL APPRECIATION": "ЭКСКЛЮЗИВНЫЙ РОСТ СТОИМОСТИ",
    "3,500+ Pro Users": "3 500+ профессиональных пользователей",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "НАЧНИТЕ СВОЕ ПУТЕШЕСТВИЕ С AA REAL ESTATE",
    "Luxury Real Estate Across the UAE": "Элитная недвижимость по всему ОАЭ",
    "Explore Properties": "Исследовать варианты",
    "Book A Consultation": "Забронировать консультацию",
    "Why Us?": "Почему мы?",
    "Why AA Real Estate?": "Почему AA Real Estate?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Ваша жизнь меняется. Не просто ищите жилье — найдите то, что будет дальше. Мы помогаем вам двигаться вперед с ясностью, уверенностью и правильным агентом рядом.",
    "This isn’t just about real estate.": "Дело не только в недвижимости.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "Это про индивидуальность. Прогресс. Движение вперед. Вы не просто ищете жилье. Вы ищете гармонию. Именно это мы помогаем вам обрести.",
  },
  ar: {
    buy: "شراء",
    rent: "إيجار",
    newProjects: "مشاريع جديدة",
    toolsInsights: "أدوات ورؤى",
    findAgents: "البحث عن وكلاء",
    loginSignup: "تسجيل الدخول / الاشتراك",
    savedProperties: "العقارات المحفوظة",
    exploreBlog: "استكشاف المدونة",
    searchPlaceholder: "البحث عن العقارات...",
    allCategories: "جميع الفئات",
    apartments: "شقق",
    villas: "فلل",
    townhouses: "تاون هاوس",
    penthouses: "بنتهاوس",
    plots: "أراضي",
    beds: "غرف نوم",
    baths: "حمامات",
    area: "المساحة",
    priceRange: "نطاق السعر",
    searchButton: "البحث عن عقار",
    overview: "نظرة عامة",
    amenities: "المرافق والخدمات",
    paymentPlan: "خطة الدفع",
    location: "الموقع والمناطق المجاورة",
    pricesTrends: "الأسعار والاتجاهات",
    similarProperties: "عقارات مماثلة",
    propertyPrice: "سعر العقار",
    contactAgent: "اتصل بالوكيل",
    sendInquiry: "إرسال استفسار",
    callUs: "اتصل بنا",
    chat: "المحادثة",
    save: "حفظ",
    saved: "تم الحفظ",
    mortgageCalculator: "حاسبة التمويل العقاري",
    downPayment: "الدفعة المقدمة",
    interestRate: "نسبة الفائدة",
    loanTerm: "مدة القرض",
    monthlyPayment: "القسط الشهري المتوقع",
    upfrontCosts: "التكاليف الإضافية",
    dldFee: "رسوم دائرة الأراضي والأملاك (4%)",
    agencyFee: "عمولة الوكالة (2%)",
    mortgageRegistration: "تسجيل الرهن العقاري (0.25%)",
    totalUpfrontRequired: "إجمالي المبلغ المطلوب مقدماً",
    verifiedAgent: "وكيل معتمد",
    responseTime: "سرعة الرد",
    languagesSpoken: "اللغات المتحدثة",
    whatsApp: "واتساب",
    all: "الكل",
    searchTitle: "اكتشف الحياة الفاخرة في الإمارات",
    searchSubtitle: "استكشف مجموعتنا المختارة من الشقق والفلل والبنتهاوس الفاخرة.",
    reset: "إعادة ضبط الفلاتر",
    sortBy: "ترتيب حسب",
    default: "الافتراضي",
    priceAsc: "السعر: من الأقل للأعلى",
    priceDesc: "السعر: من الأعلى للأقل",
    "Discover Extraordinary Living Across UAE": "اكتشف الحياة الاستثنائية في الإمارات",
    "AA Real Estate DEVELOPMENTS": "مشاريع إيه إيه العقارية",
    "Luxury Villas Designed For Elevated Living": "فلل فاخرة مصممة لحياة راقية",
    "UNRIVALED SOPHISTICATION": "رقي لا مثيل له",
    "Premium Apartments In Prime Locations": "شقق فاخرة في مواقع متميزة",
    "CURATED URBAN LIVING": "حياة حضرية منسقة",
    "Smart Property Discovery Experience": "تجربة ذكية لاكتشاف العقارات",
    "AI-POWERED SEARCH": "بحث مدعوم بالذكاء الاصطناعي",
    "Where Investment Meets Lifestyle": "حيث يلتقي الاستثمار بنمط الحياة",
    "GENERATE SECURE WEALTH": "إنشاء ثروة آمنة",
    "Invest In UAE’s Future Landmarks": "استثمر في معالم المستقبل في الإمارات",
    "EXCLUSIVE CAPITAL APPRECIATION": "نمو حصري لرأس المال",
    "3,500+ Pro Users": "أكثر من ٣٥٠٠ مستخدم محترف",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "ابدأ رحلتك مع إيه إيه العقارية",
    "Luxury Real Estate Across the UAE": "عقارات فاخرة في جميع أنحاء الإمارات",
    "Explore Properties": "استكشاف العقارات",
    "Book A Consultation": "حجز استشارة",
    "Why Us?": "لماذا نحن؟",
    "Why AA Real Estate?": "لماذا إيه إيه العقارية؟",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "حياتك تتغير. لا تبحث عن مجرد مكان — ابحث عن خطوتك التالية. نساعدك على المضي قدماً بوضوح وثقة ومع الوكيل المناسب بجانبك.",
    "This isn’t just about real estate.": "الأمر لا يتعلق فقط بالعقارات.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "الأمر يتعلق بالهوية. بالتقدم. بالتخلص من الركود. أنت لا تبحث عن مجرد مكان. أنت تبحث عن التوافق. وهذا ما نساعدك في العثور عليه.",
  },
  vi: {
    buy: "Mua",
    rent: "Thuê",
    newProjects: "Dự án mới",
    toolsInsights: "Công cụ & Ý kiến",
    findAgents: "Tìm đại lý",
    loginSignup: "Đăng nhập / Đăng ký",
    savedProperties: "Đã lưu",
    exploreBlog: "Khám phá Blog",
    searchPlaceholder: "Tìm kiếm bất động sản...",
    allCategories: "Tất cả danh mục",
    apartments: "Căn hộ",
    villas: "Biệt thự",
    townhouses: "Nhà phố",
    penthouses: "Căn hộ thông tầng",
    plots: "Lô đất",
    beds: "Phòng ngủ",
    baths: "Phòng tắm",
    area: "Diện tích",
    priceRange: "Mức giá",
    searchButton: "Tìm kiếm",
    overview: "Tổng quan",
    amenities: "Tiện ích",
    paymentPlan: "Kế hoạch thanh toán",
    location: "Vị trí & Lân cận",
    pricesTrends: "Giá & Xu hướng",
    similarProperties: "Bất động sản tương tự",
    propertyPrice: "Giá bất động sản",
    contactAgent: "Liên hệ Đại lý",
    sendInquiry: "Gửi yêu cầu",
    callUs: "Gọi cho chúng tôi",
    chat: "Trò chuyện",
    save: "Lưu",
    saved: "Đã lưu",
    mortgageCalculator: "Tính toán thế chấp",
    downPayment: "Trả trước",
    interestRate: "Lãi suất",
    loanTerm: "Thời hạn vay",
    monthlyPayment: "Thanh toán hàng tháng",
    upfrontCosts: "Chi phí ban đầu",
    dldFee: "Phí DLD (4%)",
    agencyFee: "Phí đại lý (2%)",
    mortgageRegistration: "Đăng ký thế chấp (0.25%)",
    totalUpfrontRequired: "Tổng tiền mặt cần thiết",
    verifiedAgent: "Đại lý đã xác minh",
    responseTime: "Thời gian trả lời",
    languagesSpoken: "Ngôn ngữ nói",
    whatsApp: "WhatsApp",
    all: "Tất cả",
    searchTitle: "Khám phá cuộc sống xa hoa tại UAE",
    searchSubtitle: "Khám phá bộ sưu tập căn hộ, biệt thự và penthouse đẳng cấp của chúng tôi.",
    reset: "Đặt lại bộ lọc",
    sortBy: "Sắp xếp theo",
    default: "Mặc định",
    priceAsc: "Giá: Thấp đến Cao",
    priceDesc: "Giá: Cao đến Thấp",
    "Discover Extraordinary Living Across UAE": "Khám phá cuộc sống phi thường tại UAE",
    "AA Real Estate DEVELOPMENTS": "Dự án AA Real Estate",
    "Luxury Villas Designed For Elevated Living": "Biệt thự sang trọng cho cuộc sống đẳng cấp",
    "UNRIVALED SOPHISTICATION": "SỰ TINH TẾ VÔ SONG",
    "Premium Apartments In Prime Locations": "Căn hộ cao cấp tại vị trí đắc địa",
    "CURATED URBAN LIVING": "CUỘC SỐNG ĐÔ THỊ ĐẲNG CẤP",
    "Smart Property Discovery Experience": "Trải nghiệm tìm kiếm bất động sản thông minh",
    "AI-POWERED SEARCH": "TÌM KIẾM BẰNG CÔNG NGHỆ AI",
    "Where Investment Meets Lifestyle": "Nơi đầu tư gặp gỡ phong cách sống",
    "GENERATE SECURE WEALTH": "TẠO DỰNG TÀI SẢN AN TOÀN",
    "Invest In UAE’s Future Landmarks": "Đầu tư vào các biểu tượng tương lai của UAE",
    "EXCLUSIVE CAPITAL APPRECIATION": "TĂNG TRƯỞNG GIÁ TRỊ TÀI SẢN ĐỘC QUYỀN",
    "3,500+ Pro Users": "Hơn 3.500 người dùng chuyên nghiệp",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "BẮT ĐẦU HÀNH TRÌNH VỚI AA REAL ESTATE",
    "Luxury Real Estate Across the UAE": "Bất động sản xa hoa trên toàn UAE",
    "Explore Properties": "Khám phá dự án",
    "Book A Consultation": "Đặt lịch tư vấn",
    "Why Us?": "Tại sao chọn chúng tôi?",
    "Why AA Real Estate?": "Tại sao chọn AA Real Estate?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Cuộc sống của bạn đang thay đổi. Đừng chỉ tìm một nơi ở — hãy tìm bước đi tiếp theo. Chúng tôi giúp bạn tiến về phía trước với sự rõ ràng, tự tin và đại lý phù hợp bên cạnh.",
    "This isn’t just about real estate.": "Đây không chỉ là về bất động sản.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "Đó là về bản sắc. Sự tiến bộ. Không ngừng tiến bước. Bạn không chỉ tìm kiếm một nơi ở. Bạn đang tìm kiếm sự đồng điệu. Đó là những gì chúng tôi giúp bạn tìm thấy.",
  },
  tr: {
    buy: "Satın Al",
    rent: "Kiralık",
    newProjects: "Yeni Projeler",
    toolsInsights: "Araçlar & Analizler",
    findAgents: "Temsilci Bul",
    loginSignup: "Giriş Yap / Üye Ol",
    savedProperties: "Kaydedilenler",
    exploreBlog: "Bloğu İncele",
    searchPlaceholder: "Emlak ara...",
    allCategories: "Tüm Kategoriler",
    apartments: "Daireler",
    villas: "Villalar",
    townhouses: "Sıra Evler",
    penthouses: "Çatı Katları",
    plots: "Arsalar",
    beds: "Yatak Odası",
    baths: "Banyo",
    area: "Alan",
    priceRange: "Fiyat Aralığı",
    searchButton: "Emlak Bul",
    overview: "Genel Bakış",
    amenities: "Özellikler",
    paymentPlan: "Ödeme Planı",
    location: "Konum & Yakın Çevre",
    pricesTrends: "Fiyatlar & Trendler",
    similarProperties: "Benzer İlanlar",
    propertyPrice: "Emlak Fiyatı",
    contactAgent: "Temsilciyle İletişim",
    sendInquiry: "Talep Gönder",
    callUs: "Bizi Arayın",
    chat: "Sohbet",
    save: "Kaydet",
    saved: "Kaydedildi",
    mortgageCalculator: "Kredi Hesaplama",
    downPayment: "Peşinat",
    interestRate: "Faiz Oranı",
    loanTerm: "Kredi Vadesi",
    monthlyPayment: "Aylık Ödeme Tutarı",
    upfrontCosts: "Ek Masraflar",
    dldFee: "Tapu Harcı DLD (%4)",
    agencyFee: "Emlakçı Komisyonu (%2)",
    mortgageRegistration: "Kredi Tescil Harcı (%0.25)",
    totalUpfrontRequired: "Toplam Peşin Ödeme",
    verifiedAgent: "Onaylı Temsilci",
    responseTime: "Yanıt Süresi",
    languagesSpoken: "Konuşulan Diller",
    whatsApp: "WhatsApp",
    all: "Tümü",
    searchTitle: "BAE'de Lüks Yaşamı Keşfedin",
    searchSubtitle: "Seçkin daire, villa ve çatı katı koleksiyonumuzu inceleyin.",
    reset: "Filtreleri Sıfırla",
    sortBy: "Sıralama",
    default: "Varsayılan",
    priceAsc: "Fiyat: Düşükten Yükseğe",
    priceDesc: "Fiyat: Yüksekten Düşüğe",
    "Discover Extraordinary Living Across UAE": "BAE'de Sıra Dışı Yaşamı Keşfedin",
    "AA Real Estate DEVELOPMENTS": "AA Real Estate PROJELERİ",
    "Luxury Villas Designed For Elevated Living": "Yüksek Yaşam Standardı İçin Tasarlanmış Lüks Villalar",
    "UNRIVALED SOPHISTICATION": "BENZERSİZ ZARAFET",
    "Premium Apartments In Prime Locations": "Seçkin Lokasyonlarda Premium Daireler",
    "CURATED URBAN LIVING": "SEÇKİN ŞEHİR YAŞAMI",
    "Smart Property Discovery Experience": "Akıllı Emlak Keşif Deneyimi",
    "AI-POWERED SEARCH": "YAPAY ZEKÂ DESTEKLİ ARAMA",
    "Where Investment Meets Lifestyle": "Yatırımın Yaşam Tarzıyla Buluştuğu Yer",
    "GENERATE SECURE WEALTH": "GÜVENLİ SERVET YARATIN",
    "Invest In UAE’s Future Landmarks": "BAE'nin Gelecekteki Simgelerine Yatırım Yapın",
    "EXCLUSIVE CAPITAL APPRECIATION": "ÖZEL SERMAYE DEĞER KAZANIMI",
    "3,500+ Pro Users": "3.500+ Profesyonel Kullanıcı",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "AA REAL ESTATE İLE YOLCULUĞUNUZA BAŞLAYIN",
    "Luxury Real Estate Across the UAE": "BAE Genelinde Lüks Gayrimenkul",
    "Explore Properties": "Emlakları İncele",
    "Book A Consultation": "Danışmanlık Randevusu Al",
    "Why Us?": "Neden Biz?",
    "Why AA Real Estate?": "Neden AA Real Estate?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Hayatınız değişiyor. Sadece bir yer bulmakla kalmayın, geleceğinizi keşfedin. Yanınızdaki doğru temsilciyle netlik ve güven içinde ilerlemenize yardımcı oluyoruz.",
    "This isn’t just about real estate.": "Bu sadece gayrimenkulle ilgili değil.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "Bu kimlikle ilgili. Gelişimle ilgili. Tıkanmışlıktan kurtulmakla ilgili. Sadece bir yer aramıyorsunuz. Uyum arıyorsunuz. Bulmanıza yardımcı olduğumuz şey tam olarak bu.",
  },
  es: {
    buy: "Comprar",
    rent: "Alquilar",
    newProjects: "Proyectos Nuevos",
    toolsInsights: "Herramientas",
    findAgents: "Buscar Agentes",
    loginSignup: "Iniciar Sesión",
    savedProperties: "Guardados",
    exploreBlog: "Explorar Blog",
    searchPlaceholder: "Buscar propiedades...",
    allCategories: "Categorías",
    apartments: "Apartamentos",
    villas: "Villas",
    townhouses: "Casas adosadas",
    penthouses: "Áticos",
    plots: "Terrenos",
    beds: "Hab.",
    baths: "Baños",
    area: "Área",
    priceRange: "Rango de Precios",
    searchButton: "Buscar Propiedades",
    overview: "Resumen",
    amenities: "Servicios",
    paymentPlan: "Plan de Pago",
    location: "Ubicación",
    pricesTrends: "Precios y Tendencias",
    similarProperties: "Propiedades Similares",
    propertyPrice: "Precio de la Propiedad",
    contactAgent: "Contactar Agente",
    sendInquiry: "Enviar Solicitud",
    callUs: "Llamar",
    chat: "Chat",
    save: "Guardar",
    saved: "Guardado",
    mortgageCalculator: "Calculadora de Hipoteca",
    downPayment: "Enganche",
    interestRate: "Tasa de Interés",
    loanTerm: "Plazo del Crédito",
    monthlyPayment: "Pago Mensual Estimado",
    upfrontCosts: "Gastos Iniciales",
    dldFee: "Tarifa DLD (4%)",
    agencyFee: "Comisión de Agencia (2%)",
    mortgageRegistration: "Registro Hipotecario (0.25%)",
    totalUpfrontRequired: "Total Efectivo Inicial",
    verifiedAgent: "Agente Verificado",
    responseTime: "Tiempo de Respuesta",
    languagesSpoken: "Idiomas",
    whatsApp: "WhatsApp",
    all: "Todo",
    searchTitle: "Descubra la Vida de Lujo en EAU",
    searchSubtitle: "Explore nuestra colección exclusiva de apartamentos, villas y áticos.",
    reset: "Limpiar Filtros",
    sortBy: "Ordenar Por",
    default: "Por Defecto",
    priceAsc: "Precio: Menor a Mayor",
    priceDesc: "Precio: Mayor a Menor",
    "Discover Extraordinary Living Across UAE": "Descubra una vida extraordinaria en los EAU",
    "AA Real Estate DEVELOPMENTS": "Desarrollos de AA Real Estate",
    "Luxury Villas Designed For Elevated Living": "Villas de lujo diseñadas para una vida elevada",
    "UNRIVALED SOPHISTICATION": "SOFISTICACIÓN SIN IGUAL",
    "Premium Apartments In Prime Locations": "Apartamentos premium en ubicaciones privilegiadas",
    "CURATED URBAN LIVING": "VIDA URBANA SELECCIONADA",
    "Smart Property Discovery Experience": "Experiencia de búsqueda inteligente de propiedades",
    "AI-POWERED SEARCH": "BÚSQUEDA IMPULSADA POR IA",
    "Where Investment Meets Lifestyle": "Donde la inversión se encuentra con el estilo de vida",
    "GENERATE SECURE WEALTH": "GENERE RIQUEZA SEGURA",
    "Invest In UAE’s Future Landmarks": "Invierta en los futuros hitos de los EAU",
    "EXCLUSIVE CAPITAL APPRECIATION": "APRECIACIÓN EXCLUSIVA DE CAPITAL",
    "3,500+ Pro Users": "Más de 3500 usuarios profesionales",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "COMIENCE SU VIAJE CON AA REAL ESTATE",
    "Luxury Real Estate Across the UAE": "Bienes raíces de lujo en todos los EAU",
    "Explore Properties": "Explorar propiedades",
    "Book A Consultation": "Reservar consulta",
    "Why Us?": "¿Por qué nosotros?",
    "Why AA Real Estate?": "¿Por qué AA Real Estate?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Su vida está cambiando. No se limite a buscar un lugar: encuentre su próximo paso. Le ayudamos a avanzar con claridad, confianza y el agente adecuado a su lado.",
    "This isn’t just about real estate.": "Esto no se trata solo de bienes raíces.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "Se trata de identidad. De progreso. De salir del estancamiento. No está buscando solo un lugar. Está buscando alineación. Eso es lo que le ayudamos a encontrar.",
  },
  de: {
    buy: "Kaufen",
    rent: "Mieten",
    newProjects: "Neue Projekte",
    toolsInsights: "Werkzeuge & Einblicke",
    findAgents: "Makler Finden",
    loginSignup: "Anmelden / Registrieren",
    savedProperties: "Gespeichert",
    exploreBlog: "Blog Erkunden",
    searchPlaceholder: "Immobilien suchen...",
    allCategories: "Alle Kategorien",
    apartments: "Wohnungen",
    villas: "Villen",
    townhouses: "Reihenhäuser",
    penthouses: "Penthäuser",
    plots: "Grundstücke",
    beds: "Zimmer",
    baths: "Bäder",
    area: "Fläche",
    priceRange: "Preisspanne",
    searchButton: "Immobilien Suchen",
    overview: "Übersicht",
    amenities: "Ausstattung",
    paymentPlan: "Zahlungsplan",
    location: "Lage & Umgebung",
    pricesTrends: "Preise & Trends",
    similarProperties: "Ähnliche Immobilien",
    propertyPrice: "Immobilienpreis",
    contactAgent: "Makler Kontaktieren",
    sendInquiry: "Anfrage Senden",
    callUs: "Anrufen",
    chat: "Chat",
    save: "Merken",
    saved: "Gemerkt",
    mortgageCalculator: "Hypothekenrechner",
    downPayment: "Anzahlung",
    interestRate: "Zinssatz",
    loanTerm: "Laufzeit",
    monthlyPayment: "Monatliche Rate",
    upfrontCosts: "Nebenkosten",
    dldFee: "DLD-Gebühr (4%)",
    agencyFee: "Maklergebühr (2%)",
    mortgageRegistration: "Hypothekenregistrierung (0.25%)",
    totalUpfrontRequired: "Benötigtes Eigenkapital",
    verifiedAgent: "Zertifizierter Makler",
    responseTime: "Antwortzeit",
    languagesSpoken: "Sprachen",
    whatsApp: "WhatsApp",
    all: "Alle",
    searchTitle: "Luxuriöses Wohnen in den VAE Entdecken",
    searchSubtitle: "Erkunden Sie unsere exklusive Kollektion von Wohnungen, Villen und Penthäusern.",
    reset: "Filter Zurücksetzen",
    sortBy: "Sortieren Nach",
    default: "Standard",
    priceAsc: "Preis: Aufsteigend",
    priceDesc: "Preis: Absteigend",
    "Discover Extraordinary Living Across UAE": "Entdecken Sie außergewöhnliches Wohnen in den VAE",
    "AA Real Estate DEVELOPMENTS": "AA Real Estate PROJEKTE",
    "Luxury Villas Designed For Elevated Living": "Luxusvillen für gehobenes Wohnen",
    "UNRIVALED SOPHISTICATION": "UNERREICHTE RAFFINESSE",
    "Premium Apartments In Prime Locations": "Premium-Wohnungen in erstklassigen Lagen",
    "CURATED URBAN LIVING": "KURATIERTES STÄDTISCHES WOHNEN",
    "Smart Property Discovery Experience": "Intelligente Immobiliensuche",
    "AI-POWERED SEARCH": "KI-GESTÜTZTE SUCHE",
    "Where Investment Meets Lifestyle": "Wo Investition auf Lebensstil trifft",
    "GENERATE SECURE WEALTH": "SICHEREN WOHLSTAND SCHAFFEN",
    "Invest In UAE’s Future Landmarks": "Investieren Sie in die zukünftigen Wahrzeichen der VAE",
    "EXCLUSIVE CAPITAL APPRECIATION": "EXKLUSIVER WERTHUWACHS",
    "3,500+ Pro Users": "Über 3.500 Pro-Nutzer",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "BEGINNEN SIE IHRE REISE MIT AA REAL ESTATE",
    "Luxury Real Estate Across the UAE": "Luxusimmobilien in den gesamten VAE",
    "Explore Properties": "Immobilien erkunden",
    "Book A Consultation": "Beratung vereinbaren",
    "Why Us?": "Warum wir?",
    "Why AA Real Estate?": "Warum AA Real Estate?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Ihr Leben verändert sich. Suchen Sie nicht nur eine Unterkunft – finden Sie Ihr nächstes Kapitel. Wir helfen Ihnen, mit Klarheit, Vertrauen und dem richtigen Makler an Ihrer Seite voranzukommen.",
    "This isn’t just about real estate.": "Es geht nicht nur um Immobilien.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "Es geht um Identität. Fortschritt. Vorankommen. Sie suchen nicht nur ein Zuhause. Sie suchen nach Einklang. Genau das helfen wir Ihnen zu finden.",
  },
  fr: {
    buy: "Acheter",
    rent: "Louer",
    newProjects: "Projets Neufs",
    toolsInsights: "Outils",
    findAgents: "Trouver des Agents",
    loginSignup: "Connexion",
    savedProperties: "Favoris",
    exploreBlog: "Explorer le Blog",
    searchPlaceholder: "Rechercher...",
    allCategories: "Catégories",
    apartments: "Appartements",
    villas: "Villas",
    townhouses: "Maisons de ville",
    penthouses: "Penthouses",
    plots: "Terrains",
    beds: "Chambres",
    baths: "Bains",
    area: "Surface",
    priceRange: "Budget",
    searchButton: "Rechercher",
    overview: "Aperçu",
    amenities: "Équipements",
    paymentPlan: "Plan de Paiement",
    location: "Emplacement",
    pricesTrends: "Prix & Tendances",
    similarProperties: "Biens Similaires",
    propertyPrice: "Prix du Bien",
    contactAgent: "Contacter l'Agent",
    sendInquiry: "Envoyer Demande",
    callUs: "Appeler",
    chat: "Discuter",
    save: "Enregistrer",
    saved: "Enregistré",
    mortgageCalculator: "Calcul de Prêt",
    downPayment: "Apport Personnel",
    interestRate: "Taux d'Intérêt",
    loanTerm: "Durée du Prêt",
    monthlyPayment: "Mensualité Estimée",
    upfrontCosts: "Frais Annexes",
    dldFee: "Frais DLD (4%)",
    agencyFee: "Frais d'Agence (2%)",
    mortgageRegistration: "Enregistrement Hypothèque (0.25%)",
    totalUpfrontRequired: "Total Apport Nécessaire",
    verifiedAgent: "Agent Certifié",
    responseTime: "Temps de Réponse",
    languagesSpoken: "Langues Parlées",
    whatsApp: "WhatsApp",
    all: "Tous",
    searchTitle: "Découvrez l'Art de Vivre aux EAU",
    searchSubtitle: "Explorez notre collection exclusive d'appartements, villas et penthouses de prestige.",
    reset: "Réinitialiser",
    sortBy: "Trier Par",
    default: "Par Défaut",
    priceAsc: "Prix: Croissant",
    priceDesc: "Prix: Décroissant",
    "Discover Extraordinary Living Across UAE": "Découvrez une vie extraordinaire aux Émirats Arabes Unis",
    "AA Real Estate DEVELOPMENTS": "Développements AA Real Estate",
    "Luxury Villas Designed For Elevated Living": "Villas de luxe conçues pour une vie surélevée",
    "UNRIVALED SOPHISTICATION": "SOPHISTICATION INÉGALÉE",
    "Premium Apartments In Prime Locations": "Appartements premium dans des emplacements de choix",
    "CURATED URBAN LIVING": "VIE URBAINE CURATÉE",
    "Smart Property Discovery Experience": "Expérience de recherche immobilière intelligente",
    "AI-POWERED SEARCH": "RECHERCHE PROULSÉE PAR L'IA",
    "Where Investment Meets Lifestyle": "Là où l'investissement rencontre le style de vie",
    "GENERATE SECURE WEALTH": "CRÉER UNE RICHESSE SÉCURISÉE",
    "Invest In UAE’s Future Landmarks": "Investissez dans les futurs monuments des EAU",
    "EXCLUSIVE CAPITAL APPRECIATION": "VALORISATION EXCLUSIVE DU CAPITAL",
    "3,500+ Pro Users": "Plus de 3 500 utilisateurs pro",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "COMMENCEZ VOTRE VOYAGE AVEC AA REAL ESTATE",
    "Luxury Real Estate Across the UAE": "Immobilier de luxe dans tous les EAU",
    "Explore Properties": "Explorer les biens",
    "Book A Consultation": "Réserver une consultation",
    "Why Us?": "Pourquoi nous ?",
    "Why AA Real Estate?": "Pourquoi AA Real Estate ?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "Votre vie change. Ne cherchez pas seulement un endroit — trouvez la suite. Nous vous aidons à aller de l'avant avec clarté, confiance et le bon agent à vos côtés.",
    "This isn’t just about real estate.": "Il ne s'agit pas seulement d'immobilier.",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "C'est une question d'identité. De progrès. De déblocage. Vous ne cherchez pas seulement un endroit. Vous cherchez l'alignement. C'est ce que nous vous aidons à trouver.",
  },
  hi: {
    buy: "खरीदें",
    rent: "किराया",
    newProjects: "नई परियोजनाएं",
    toolsInsights: "टूल्स और अंतर्दृष्टि",
    findAgents: "एजेंट खोजें",
    loginSignup: "लॉगिन / साइनअप",
    savedProperties: "सहेजे गए",
    exploreBlog: "ब्लॉग देखें",
    searchPlaceholder: "संपत्ति खोजें...",
    allCategories: "सभी श्रेणियां",
    apartments: "अपार्टमेंट",
    villas: "विला",
    townhouses: "टाउनहाउस",
    penthouses: "पेंटहाउस",
    plots: "भूखंड / प्लॉट",
    beds: "बेडरूम",
    baths: "बाथरूम",
    area: "क्षेत्रफल",
    priceRange: "बजट",
    searchButton: "संपत्ति खोजें",
    overview: "विवरण",
    amenities: "सुविधाएं",
    paymentPlan: "भुगतान योजना",
    location: "स्थान",
    pricesTrends: "कीमतें और रुझान",
    similarProperties: "समान संपत्तियां",
    propertyPrice: "संपत्ति की कीमत",
    contactAgent: "एजेंट से संपर्क करें",
    sendInquiry: "पूछताछ भेजें",
    callUs: "कॉल करें",
    chat: "चैट करें",
    save: "सहेजें",
    saved: "सहेजा गया",
    mortgageCalculator: "होम लोन कैलकुलेटर",
    downPayment: "डाउन पेमेंट",
    interestRate: "ब्याज दर",
    loanTerm: "ऋण की अवधि",
    monthlyPayment: "अनुमानित मासिक किस्त",
    upfrontCosts: "प्रारंभिक लागतें",
    dldFee: "DLD शुल्क (4%)",
    agencyFee: "एजेंसी ब्रोकरेज (2%)",
    mortgageRegistration: "लोन पंजीकरण (0.25%)",
    totalUpfrontRequired: "कुल आवश्यक नकद भुगतान",
    verifiedAgent: "सत्यापित एजेंट",
    responseTime: "जवाब देने का समय",
    languagesSpoken: "बोली जाने वाली भाषाएं",
    whatsApp: "व्हाट्सएप",
    all: "सभी",
    searchTitle: "यूएई में शानदार जीवनशैली की खोज करें",
    searchSubtitle: "असाधारण अपार्टमेंट, विला और पेंटहाउस के हमारे चुनिंदा संग्रह को देखें।",
    reset: "फ़िल्टर रीसेट करें",
    sortBy: "क्रमबद्ध करें",
    default: "डिफ़ॉल्ट",
    priceAsc: "कीमत: कम से अधिक",
    priceDesc: "कीमत: अधिक से कम",
    "Discover Extraordinary Living Across UAE": "यूएई में असाधारण जीवनशैली की खोज करें",
    "AA Real Estate DEVELOPMENTS": "एए रियल एस्टेट डेवलपमेंट्स",
    "Luxury Villas Designed For Elevated Living": "उन्नत जीवनशैली के लिए डिज़ाइन किए गए शानदार विला",
    "UNRIVALED SOPHISTICATION": "बेजोड़ परिष्कार",
    "Premium Apartments In Prime Locations": "प्रमुख स्थानों पर प्रीमियम अपार्टमेंट",
    "CURATED URBAN LIVING": "क्यूरेटेड शहरी जीवन",
    "Smart Property Discovery Experience": "स्मार्ट संपत्ति खोज का अनुभव",
    "AI-POWERED SEARCH": "एआई-संचालित खोज",
    "Where Investment Meets Lifestyle": "जहां निवेश और जीवनशैली का मिलन होता है",
    "GENERATE SECURE WEALTH": "सुरक्षित संपत्ति का निर्माण करें",
    "Invest In UAE’s Future Landmarks": "यूएई के भविष्य के ऐतिहासिक स्थलों में निवेश करें",
    "EXCLUSIVE CAPITAL APPRECIATION": "विशेष पूंजी वृद्धि",
    "3,500+ Pro Users": "3,500+ प्रो उपयोगकर्ता",
    "BEGIN YOUR JOURNEY WITH AA REAL ESTATE": "एए रियल एस्टेट के साथ अपनी यात्रा शुरू करें",
    "Luxury Real Estate Across the UAE": "पूरे यूएई में लक्जरी रियल एस्टेट",
    "Explore Properties": "संपत्तियों का अन्वेषण करें",
    "Book A Consultation": "परामर्श बुक करें",
    "Why Us?": "हम क्यों?",
    "Why AA Real Estate?": "एए रियल एस्टेट क्यों?",
    "Your life's changing. Don't just find a place — find what's next. We help you move forward with clarity, confidence, and the right agent by your side.": "आपका जीवन बदल रहा है। केवल एक जगह न खोजें - बल्कि अपना अगला कदम खोजें। हम आपके साथ सही एजेंट के होने से स्पष्टता और आत्मविश्वास के साथ आगे बढ़ने में आपकी मदद करते हैं।",
    "This isn’t just about real estate.": "यह केवल रियल एस्टेट के बारे में नहीं है।",
    "It’s about identity. Progress. Getting unstuck. You’re not just looking for a place. You’re looking for alignment. That’s what we help you find.": "यह पहचान के बारे में है। प्रगति के बारे में है। ठहराव से बाहर निकलने के बारे में है। आप केवल एक जगह नहीं तलाश रहे हैं। आप तालमेल की तलाश कर रहे हैं। यही हम आपको खोजने में मदद करते हैं।",
  },
  // Extra language fallbacks defaulting to English
  bg: {}, cz: {}, dk: {}, el: {}, fi: {}, hu: {}, id: {}, it: {}, ja: {}, ko: {}, nl: {}, no: {}, pl: {}, pt: {}
};

// Populate default fallback dictionary translations from English for missing ones
Object.keys(DICTIONARY).forEach((langKey) => {
  const code = langKey as LanguageCode;
  if (code !== "en") {
    Object.keys(DICTIONARY.en).forEach((key) => {
      if (!DICTIONARY[code][key]) {
        DICTIONARY[code][key] = DICTIONARY.en[key];
      }
    });
  }
});

// Dynamic property word translator
const PROPERTY_TRANSLATIONS: Record<string, Record<string, string>> = {
  ru: {
    "Palm Jumeirah": "Пальма Джумейра",
    "Dubai Water Canal": "Дубайский Водный Канал",
    "Jumeirah Bay Island": "Остров Джумейра Бэй",
    "Business Bay": "Бизнес Бэй",
    "Mohammed Bin Rashid City": "مدينة محمد بن راشد",
    "Emaar Beachfront": "Эмаар Бичфронт",
    "DIFC": "DIFC (Финансовый Центр)",
    "Sobha Hartland": "Собха Хартленд",
    "Dubai Hills Estate": "Дубай Хиллс Эстейт",
    "Downtown Dubai": "Даунтаун Дубай",
    "Dubai Marina": "Дубай Марина",
    "Jumeirah Golf Estates": "Джумейра Гольф Эстейтс",
    "Arabian Ranches": "Арабиан Ранчез",
    "Deira Islands": "Острова Дейра",
    "City Walk": "Сити Вок",
    "Meydan": "Мейдан",
    "Damac Hills": "Дамак Хиллс",
    "Jumeirah Beach Residence": "Джумейра Бич Резиденс",
    "Tilal Al Ghaf": "Тилаль Аль Гаф",
    "Al Barari": "Аль Барари",
    "Bluewaters Island": "Остров Блувотерс",
    "Mudon": "Мудон",
    "Za'abeel": "Заабиль",
    "Emaar South": "Эмаар Саут",
    "The Oasis": "Зе Оазис",
    "La Mer": "Ла Мер",
    "Jebel Ali": "Джебель Али",
    "Nad Al Sheba": "Над Аль Шеба",
    "Damac Lagoons": "Дамак Лагунс",
    "Dubai Creek Harbour": "Дубай Крик Харбор",
    "Dubai": "Дубай",
    "UAE": "ОАЭ",
    "The Royal Atlantis Signature Penthouse": "Фирменный пентхаус The Royal Atlantis",
    "One Canal Ultra-Luxury Villa": "Ультра-роскошная вилла One Canal",
    "Bulgari Resort Loft Residence": "Резиденция Bulgari Resort Loft",
    "Vela Viento Sky Residences": "Небесные резиденции Vela Viento",
    "District One Crystal Mansion": "Хрустальный особняк District One",
    "Emaar Beachfront Sky Villa": "Небесная вилла Emaar Beachfront",
    "DIFC Executive Penthouse": "Представительский пентхаус DIFC",
    "Sobha Hartland Forest Villas": "Лесные виллы Sobha Hartland",
    "Jumeirah Bay Island Waterfront Plot": "Участок у воды на Jumeirah Bay Island",
    "Dubai Hills Estate Grand Townhouse": "Большой таунхаус в Dubai Hills Estate",
    "Palm Jumeirah Waterfront Mansion": "Особняк у воды на Palm Jumeirah",
    "Downtown Boulevard Luxury Apartment": "Роскошные апартаменты Downtown Boulevard",
    "Marina Gate Penthouse Duplex": "Двухуровневый пентхаус Marina Gate",
    "Jumeirah Golf Estates Villa": "Вилла в Jumeirah Golf Estates",
    "Arabian Ranches Family Townhouse": "Семейный таунхаус в Arabian Ranches",
    "Nakheel Deira Islands Beachfront Villa": "Пляжная вилла Nakheel Deira Islands",
    "City Walk Modern Studio Apartment": "Современная квартира-студия City Walk",
    "Meydan Avenue Signature Townhouse": "Фирменный таунхаус Meydan Avenue",
    "Damac Hills Golf Villa": "Гольф-вилла в Damac Hills",
    "JBR Walk Seaview Apartment": "Квартира с видом на море JBR Walk",
    "Tilal Al Ghaf Premium Villa": "Премиум-вилла в Tilal Al Ghaf",
    "Al Barari Sanctuary Estate": "Поместье-заповедник Al Barari",
    "Bluewaters Island Penthouse": "Пентхаус на Bluewaters Island",
    "Mudon Community Townhouse": "Таунхаус сообщества Mudon",
    "Zabeel Park Luxury Apartment": "Роскошная квартира в Zabeel Park",
    "Polo Residences Golf Estate": "Поло Резиденс Гольф Эстейт",
    "Creek Harbour Horizon Apartment": "Квартира Creek Harbour Horizon",
    "Emaar The Address Residences": "Резиденции Emaar The Address",
    "Emaar South Fairway Villas": "Виллы Emaar South Fairway",
    "Dubai Hills Park Lane Apartments": "Апартаменты Dubai Hills Park Lane",
    "Emaar Beachfront Marina Vista": "Emaar Beachfront Marina Vista",
    "Emaar The Oasis Luxury Villa": "Роскошная вилла Emaar The Oasis",
    "Emaar Golf Heights Penthouse": "Пентхаус Emaar Golf Heights",
    "Emaar Harbour Views Tower": "Башня Emaar Harbour Views",
    "La Mer Beachfront Apartments": "Пляжные апартаменты La Mer",
    "Port De La Mer Marina Penthouse": "Марина Пентхаус Port De La Mer",
    "Bluewaters Bay Island Residence": "Резиденция Bluewaters Bay Island",
    "City Walk Boulevard Loft": "Лофт City Walk Boulevard",
    "Bvlgari Marina Loft Suite": "Сьют Bvlgari Marina Loft",
    "The Beach Residence JBR": "The Beach Residence JBR",
    "Palm Jumeirah Frond Villa": "Вилла на ветви Palm Jumeirah",
    "Palm Beach Towers Apartment": "Апартаменты в Palm Beach Towers",
    "Jebel Ali Village Townhouse": "Таунхаус в Jebel Ali Village",
    "The Palm Tower Sky Suite": "Небесный сьют The Palm Tower",
    "Nad Al Sheba Villa Community": "Сообщество вилл Nad Al Sheba",
    "Deira Islands Shoreline Apartment": "Береговая квартира на Deira Islands",
  },
  ar: {
    "Palm Jumeirah": "نخلة جميرا",
    "Dubai Water Canal": "قناة دبي المائية",
    "Jumeirah Bay Island": "جزيرة خليج جميرا",
    "Business Bay": "الخليج التجاري",
    "Mohammed Bin Rashid City": "مدينة محمد بن راشد",
    "Emaar Beachfront": "إعمار بيتشفرونت",
    "DIFC": "مركز دبي المالي العالمي",
    "Sobha Hartland": "شوبا هارتلاند",
    "Dubai Hills Estate": "دبي هيلز إستيت",
    "Downtown Dubai": "وسط مدينة دبي",
    "Dubai Marina": "مرسى دبي",
    "Jumeirah Golf Estates": "عقارات جميرا للجولف",
    "Arabian Ranches": "المرابع العربية",
    "Deira Islands": "جزر ديرة",
    "City Walk": "سيتي ووك",
    "Meydan": "ميدان",
    "Damac Hills": "داماك هيلز",
    "Jumeirah Beach Residence": "جميرا بيتش ريزيدنس",
    "Tilal Al Ghaf": "تلال الغاف",
    "Al Barari": "البراري",
    "Bluewaters Island": "جزيرة بلوواترز",
    "Mudon": "مدن",
    "Za'abeel": "زعبيل",
    "Emaar South": "إعمار الجنوب",
    "The Oasis": "الواحة",
    "La Mer": "لا مير",
    "Jebel Ali": "جبل علي",
    "Nad Al Sheba": "ند الشبا",
    "Damac Lagoons": "داماك لاغونز",
    "Dubai Creek Harbour": "خور دبي",
    "Dubai": "دبي",
    "UAE": "الإمارات",
    "The Royal Atlantis Signature Penthouse": "بنتهاوس رويال أتلانتس المميز",
    "One Canal Ultra-Luxury Villa": "فيلا ون كانال فائقة الفخامة",
    "Bulgari Resort Loft Residence": "ريزيدنس بولغري ريزورت لوفت",
    "Vela Viento Sky Residences": "شقق فيلا فينتو المعلقة",
    "District One Crystal Mansion": "قصر ديستريكت ون الكريستالي",
    "Emaar Beachfront Sky Villa": "فيلا إعمار بيتشفرونت المعلقة",
    "DIFC Executive Penthouse": "بنتهاوس التنفيذي في مركز دبي المالي",
    "Sobha Hartland Forest Villas": "فلل الغابة في شوبا هارتلاند",
    "Jumeirah Bay Island Waterfront Plot": "أرض مواجهة للماء في جزيرة خليج جميرا",
    "Dubai Hills Estate Grand Townhouse": "تاون هاوس غراند في دبي هيلز",
    "Palm Jumeirah Waterfront Mansion": "قصر مواجه للمياه في نخلة جميرا",
    "Downtown Boulevard Luxury Apartment": "شقة فاخرة في داون تاون بوليفارد",
    "Marina Gate Penthouse Duplex": "بنتهاوس دوبلكس في مارينا غيت",
    "Jumeirah Golf Estates Villa": "فيلا عقارات جميرا للجولف",
    "Arabian Ranches Family Townhouse": "تاون هاوس عائلي في المرابع العربية",
    "Nakheel Deira Islands Beachfront Villa": "فيلا شاطئية في جزر ديرة من نخيل",
    "City Walk Modern Studio Apartment": "ستوديو حديث في سيتي ووك",
    "Meydan Avenue Signature Townhouse": "تاون هاوس مميز في ميدان أفينيو",
    "Damac Hills Golf Villa": "فيلا جولف في داماك هيلز",
    "JBR Walk Seaview Apartment": "شقة مطلة على البحر في ممشى جي بي آر",
    "Tilal Al Ghaf Premium Villa": "فيلا فاخرة في تلال الغاف",
    "Al Barari Sanctuary Estate": "قصر سانكتشواري في البراري",
    "Bluewaters Island Penthouse": "بنتهاوس جزيرة بلوواترز",
    "Mudon Community Townhouse": "تاون هاوس في مجمع مدن",
    "Zabeel Park Luxury Apartment": "شقة فاخرة في حديقة زعبيل",
    "Polo Residences Golf Estate": "بولو ريزيدنسز غولف إستيت",
    "Creek Harbour Horizon Apartment": "شقة هورايزون في خور دبي",
    "Emaar The Address Residences": "شقق العنوان من إعمار",
    "Emaar South Fairway Villas": "فلل فيرواي في إعمار الجنوب",
    "Dubai Hills Park Lane Apartments": "شقق بارك لين في دبي هيلز",
    "Emaar Beachfront Marina Vista": "مارينا فيستا في إعمار بيتشفرونت",
    "Emaar The Oasis Luxury Villa": "فيلا الواحة الفاخرة من إعمار",
    "Emaar Golf Heights Penthouse": "بنتهاوس جولف هايتس من إعمار",
    "Emaar Harbour Views Tower": "أبراج إعمار هاربور فيوز",
    "La Mer Beachfront Apartments": "شقق لا مير الشاطئية",
    "Port De La Mer Marina Penthouse": "بنتهاوس مارينا في بورت دو لا مير",
    "Bluewaters Bay Island Residence": "شقق خليج بلوواترز",
    "City Walk Boulevard Loft": "لوفت ممشى سيتي ووك",
    "Bvlgari Marina Loft Suite": "جناح بولغري مارينا لوفت",
    "The Beach Residence JBR": "ذا بيتش ريزيدنس جي بي آر",
    "Palm Jumeirah Frond Villa": "فيلا سعفة نخلة جميرا",
    "Palm Beach Towers Apartment": "شقة أبراج بالم بيتش",
    "Jebel Ali Village Townhouse": "تاون هاوس قرية جبل علي",
    "The Palm Tower Sky Suite": "جناح ذا بالم تاور المعلق",
    "Nad Al Sheba Villa Community": "مجمع فلل ند الشبا",
    "Deira Islands Shoreline Apartment": "شقة شاطئية في جزر ديرة",
  }
};

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("en");
  const [currency, setCurrency] = useState<CurrencyCode>("AED");

  useEffect(() => {
    const savedLang = localStorage.getItem("aa-language") as LanguageCode | null;
    if (savedLang) setLanguage(savedLang);

    const savedCurr = localStorage.getItem("aa-currency") as CurrencyCode | null;
    if (savedCurr) setCurrency(savedCurr);
  }, []);

  useEffect(() => {
    localStorage.setItem("aa-language", language);
    // RTL Handler
    const root = document.documentElement;
    if (language === "ar") {
      root.setAttribute("dir", "rtl");
      root.classList.add("rtl");
    } else {
      root.setAttribute("dir", "ltr");
      root.classList.remove("rtl");
    }
  }, [language]);

  useEffect(() => {
    localStorage.setItem("aa-currency", currency);
  }, [currency]);

  // Utility to format price based on selected currency
  const formatPrice = (priceVal: number, type?: "buy" | "rent") => {
    const conf = CURRENCY_CONVERSION[currency] || CURRENCY_CONVERSION.AED;
    const converted = priceVal * conf.rate;
    const rounded = Math.round(converted);
    const formattedNum = rounded.toLocaleString("en-US");
    const currencyPart = `${conf.prefix}${formattedNum}${conf.suffix}`;
    
    if (type === "rent") {
      // If language is Arabic, suffix in Arabic: " / شهرياً"
      const suffix = language === "ar" ? " / شهرياً" : " / month";
      return `${currencyPart}${suffix}`;
    }
    return currencyPart;
  };

  // Convert area unit based on selected language
  const formatArea = (areaStr: string) => {
    // Expected formats: "8,500 sq ft" or "11,200 sq ft"
    if (!areaStr) return "";
    
    // Is metric preferred? English US/UK uses sq ft, others use m² or м²
    const isMetric = language !== "en";
    const numPart = parseInt(areaStr.replace(/,/g, "").match(/\d+/)?.[0] || "0", 10);
    
    if (isMetric && numPart > 0) {
      const converted = Math.round(numPart / 10.764);
      const formattedNum = converted.toLocaleString("en-US");
      const unit = language === "ru" ? " м²" : " m²";
      return `${formattedNum}${unit}`;
    }
    
    return areaStr;
  };

  // Translator utility
  const t = (key: string): string => {
    if (!key) return "";
    
    // Check property title & location translations first
    const propertyLangDict = PROPERTY_TRANSLATIONS[language];
    if (propertyLangDict && propertyLangDict[key]) {
      return propertyLangDict[key];
    }
    
    // Check dictionary
    const langDict = DICTIONARY[language] || DICTIONARY.en;
    if (langDict[key]) {
      return langDict[key];
    }
    
    // Attempt keyword replacements for title/location if it's dynamic
    let translated = key;
    const mappings = PROPERTY_TRANSLATIONS[language];
    if (mappings) {
      Object.keys(mappings).forEach((engKeyword) => {
        if (engKeyword.length > 3 && translated.includes(engKeyword)) {
          translated = translated.replaceAll(engKeyword, mappings[engKeyword]);
        }
      });
    }
    return translated;
  };

  return (
    <PreferencesContext.Provider
      value={{
        language,
        setLanguage,
        currency,
        setCurrency,
        formatPrice,
        formatArea,
        t,
      }}
    >
      {children}
    </PreferencesContext.Provider>
  );
}

export const usePreferences = () => useContext(PreferencesContext);
